# A glimpse into PyTorch
[pytorch tutorial web page](https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html)

## Numpy Review

In [1]:
# numpy
import numpy as np

# 1D with Numpy
# List를 생성해서 np.array로 1차원 array로 변환함.
t = np.array([0., 1., 2., 3., 4., 5., 6.])

print(t)
print('Dim of t: ', t.ndim)
print('Shape of t: ', t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Dim of t:  1
Shape of t:  (7,)


### 1D Case

In [2]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [3]:
print('t[2:5] t[4:-1]  = ', t[1:5], t[4:-1]) # Slicing

t[2:5] t[4:-1]  =  [1. 2. 3. 4.] [4. 5.]


In [4]:
print('t[:2] t[3:]     = ', t[:2], t[3:]) 

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D case

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## Pytorch Tensor

In [7]:
import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


1차원 텐서이며, 총 7개의 element. 인덱스로 접근하는 것과 슬라이싱을 해봅시다. 

In [9]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [10]:
#2차원
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape
print(t.shape)

2
torch.Size([4, 3])
torch.Size([4, 3])


In [12]:
print(t[:, 1]) # 2nd column
print(t[:, 1].size()) # 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [13]:
print(t[:, :-1]) 

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [14]:
# 이 경우 문제가 없음. 
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1)
print(m2)
print(m1 + m2)

tensor([[3., 3.]])
tensor([[2., 2.]])
tensor([[5., 5.]])


In [15]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1)
print(m2)
print(m1 + m2)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


### Others

In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1)
print(m2)
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


### componentwise 

In [18]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1)
print(m2)
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # matmul 이 아님

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [19]:
# mean
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [21]:
print(t.mean(dim=0)) 

tensor([2., 3.])


In [22]:
print(t.mean(dim=1)) 
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [23]:
# Sum

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거 >>> 행끼리 더해준다
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [24]:
# (Max) and (ArgMax)

t = torch.FloatTensor([[1, 2, 0.5], [3, 4, 5], [8, 7, 2]])
print(t)
print(t.max()) # Returns one value: max
print('####################')
print(t.max(dim=0)) # Returns two values: max and argmax

tensor([[1.0000, 2.0000, 0.5000],
        [3.0000, 4.0000, 5.0000],
        [8.0000, 7.0000, 2.0000]])
tensor(8.)
####################
torch.return_types.max(
values=tensor([8., 7., 5.]),
indices=tensor([2, 2, 1]))


max에 dim 인자를 주면 argmax도 함께 리턴. 첫번째 열에서 8의 인덱스는 2. 두번째 열에서 5의 인덱스는 2. 그러므로 [2, 1, 1]이 리턴.

### 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 중요!!

View -  Reshape 와 같은 역할

In [25]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(t.shape)
print(ft.shape)
print("t = \n", t)
print("ft = \n", ft)

(2, 2, 3)
torch.Size([2, 2, 3])
t = 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
ft = 
 tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


이제 ft 텐서를 view를 사용하여 크기(shape)를 2차원 텐서로 변경해봅시다.

In [26]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


-1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다. 다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다. 결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.

___

이번에는 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업을 해보겠습니다. view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야 하므로, (2 × 2 × 3) 텐서를 (4 × 1 × 3) 텐서로 변경

In [27]:
print(ft.view([-1, 1, 3])) # (? x 1 x 3) 으로 변경
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 스퀴즈(Squeeze) - 1인 차원을 제거

In [28]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가

In [30]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
#현재는 차원이 1개인 1차원 벡터입니다. 여기에 첫번째 차원에 1인 차원을 추가해보겠습니다. 
#첫번째 차원의 인덱스를 의미하는 숫자 0을 인자로 넣으면 첫번째 차원에 1인 차원이 추가.
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미.
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [31]:
# 방금 한 연산을 앞서 배운 view로도 구현 가능
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [32]:
# 이번에는 unsqueeze의 인자로 1을 넣어보겠습니다. 인덱스는 0부터 시작하므로 이는 두번째 차원에 1을 추가하겠다는 것을 의미
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 타입 캐스팅(Type Casting)

자료형을 변환하는 것을 타입 캐스팅이라고 합니다.

우선 실습을 위해 long 타입의 lt라는 텐서를 선언합니다.

In [33]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [34]:
print(lt.float())

tensor([1., 2., 3., 4.])


### 연결하기(concatenate)

In [35]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


두 텐서를 torch.cat([ ])를 통해 연결

In [36]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [37]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

연결(concatenate)을 하는 또 다른 방법으로 스택킹(Stacking)이 있습니다. concatenate 함수와 stack 함수의 가장 큰 차이점은 stack 함수는 ndim을 1개 넘어서도 배열을 합칠 수 있음. 즉, matrix 뿐만 아닌 tensor의 경우도 됨

In [38]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(x,y,z)
print(x.shape,y.shape,z.shape)

tensor([1., 4.]) tensor([2., 5.]) tensor([3., 6.])
torch.Size([2]) torch.Size([2]) torch.Size([2])


In [39]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z]).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [40]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [41]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [42]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [43]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation (덮어쓰기 연산)

In [44]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


첫번째 출력은 곱하기 2가 수행된 결과를 보여주고, 두번째 출력은 기존의 값이 그대로 출력된 것을 확인할 수 있습니다. 곱하기 2를 수행했지만 이를 x에다가 다시 저장하지 않았으니, 곱하기 연산을 하더라도 기존의 값 x는 변하지 않는 것이 당연합니다.

그런데 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 합니다.

In [45]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Zip

여러 개의 순회 가능한(iterable) 객체를 인자로 받고, 각 객체가 담고 있는 원소를 터플의 형태로 차례로 접근할 수 있는 반복자(iterator)를 반환

In [46]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [47]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


In [48]:
numbers = [1, 2, 3]
letters = ["A", "B", "C"]
for pair in zip(numbers, letters):
    print(pair)

(1, 'A')
(2, 'B')
(3, 'C')


zip 함수로 여러 그룹의 데이터를 루프를 한 번만 돌면서 처리할 수 있는데요. 가변 인자를 받기 때문에 2개 이상의 인자를 넘겨서 병렬 처리를 할 수 있습니다.

In [49]:
for number, upper, lower in zip("12345", "ABCDE", "abcde"):
    print(number, upper, lower)

1 A a
2 B b
3 C c
4 D d
5 E e


### 함수(function)과 클래스(Class)의 차이

우선 add 함수를 파이썬으로 구현해보겠습니다.
result라는 전역 변수를 선언합니다.

In [50]:
result = 0
def add(num):
    global result
    result += num
    return result

print(add(3))
print(add(4))
print(add(5))

3
7
12


유명한 예시) 이번에는 독립적인 두 개의 덧셈기를 만들어보자. 첫번째 계산기로는 3+7을 하고 있고, 두번째 계산기로는 3+10을 하려고 함. 이를 함수로 구현하면 하나의 함수는 1개의 덧셈기만을 의미하므로 이 경우에는 두 개의 함수를 독립적으로 만들어야 합니다.

In [51]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


클래스를 사용해보자

In [52]:
class Calculator:
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num): # 객체 생성 후 사용할 수 있는 함수.
        self.result += num
        return self.result

In [53]:
# 클래스를 생성한 후에는 이걸로 객체라는 것을 만들 수 있다. 
cal1 = Calculator()
cal2 = Calculator()
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
