In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

In [2]:
class LinearRegressionModel(nn.Module):
    #__init__(): 객체가 갖는 속성값을 초기화하는 역할 -> 객체가 생성될 때 자동으로 호출
    # super()호출 >>>> 오버라이딩,  nn.Module 클래스의 속성들을 가지고 초기화 
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    
    #forward() :모델이 학습데이터를 입력받아서 forward 연산을 진행 -> 객체를 데이터와 함께 호출하면 자동으로 실행
    # forward 연산: H(x)  식에 입력 x로부터 예측된 y를 얻는 것
    def forward(self, x):
        return self.linear(x)

In [3]:
# df = pd.read_csv('./test-score.csv', header=None)

data_in = np.loadtxt(fname='./test-score.csv', delimiter=',')
x_train = torch.from_numpy(data_in[:, 0:3]).float()             # (N, 3)
y_train = torch.from_numpy(data_in[:, 3]).unsqueeze(1).float()  # (N, 1)

# x_train = df.iloc[:, :3].to_numpy()
# x_train = torch.from_numpy(x_train)
# x_train = x_train.type(torch.float32)
# # x_train.reshape(25, 3)
# y_train = df.iloc[:, 3].to_numpy()
# y_train = torch.from_numpy(y_train)
# y_train = y_train.type(torch.float32)
# # y_train.reshape(25, 1)

In [4]:
model = LinearRegressionModel()
# W = torch.zeros(3, requires_grad=True)
# b = torch.zeros(1, requires_grad=True)
# Set up the optimizer
# optimizer = optim.SGD([W, b], lr=1e-5)
optimizer = optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # Compute H(x)
    prediction = model(x_train)
    # Compute the cost with MSE
    cost = F.mse_loss(prediction, y_train)
    # Update H(x)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    # print epoch and cost for every 20 epochs
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].detach().numpy()
        b = params[1].detach().numpy()
        s = 'Epoch {:4d}/{} W: {}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, tuple(*W), b.item(), cost.item())
        print(s)


Epoch    0/2000 W: (0.268917, -0.08977151, 0.39426336), b: 0.151 Cost: 36952.648438
Epoch  100/2000 W: (0.735717, 0.39160162, 0.8917355), b: 0.156 Cost: 8.927736
Epoch  200/2000 W: (0.7262771, 0.39386705, 0.8986972), b: 0.156 Cost: 8.784955
Epoch  300/2000 W: (0.71707296, 0.39612663, 0.90543556), b: 0.156 Cost: 8.649653
Epoch  400/2000 W: (0.7080991, 0.39837795, 0.91195816), b: 0.156 Cost: 8.521446
Epoch  500/2000 W: (0.6993494, 0.40061942, 0.91827255), b: 0.156 Cost: 8.399905
Epoch  600/2000 W: (0.6908181, 0.40284938, 0.92438596), b: 0.156 Cost: 8.284714
Epoch  700/2000 W: (0.6824997, 0.40506613, 0.9303053), b: 0.156 Cost: 8.175515
Epoch  800/2000 W: (0.67438936, 0.40726817, 0.936037), b: 0.156 Cost: 8.071971
Epoch  900/2000 W: (0.6664814, 0.40945405, 0.9415878), b: 0.155 Cost: 7.973793
Epoch 1000/2000 W: (0.65877074, 0.4116226, 0.9469637), b: 0.155 Cost: 7.880671
Epoch 1100/2000 W: (0.65125257, 0.41377255, 0.9521709), b: 0.155 Cost: 7.792363
Epoch 1200/2000 W: (0.64392185, 0.41590318

In [12]:
# model.eval()  # model.train()

# Put the test input
new_var = torch.FloatTensor([[73, 80, 75]])
# Get the prediction value.
pred_y = model(x_train).detach().numpy()
real_y = y_train.numpy()
err = np.abs(1.0 - pred_y / real_y)
conc_y = np.hstack((pred_y, real_y, err))

with np.printoptions(precision=3, formatter={'all': lambda x: x, 'float': lambda x: f"{x:5.3f}"}):
    print(conc_y)

[[152.328 152.000 0.002]
 [185.476 185.000 0.003]
 [181.430 180.000 0.008]
 [198.519 196.000 0.013]
 [141.316 142.000 0.005]
 [105.959 101.000 0.049]
 [149.354 149.000 0.002]
 [111.693 115.000 0.029]
 [175.061 175.000 0.000]
 [164.455 164.000 0.003]
 [143.656 141.000 0.019]
 [143.079 141.000 0.015]
 [186.517 184.000 0.014]
 [153.892 152.000 0.012]
 [150.505 148.000 0.017]
 [188.885 192.000 0.016]
 [146.178 147.000 0.006]
 [179.243 183.000 0.021]
 [177.301 177.000 0.002]
 [158.566 159.000 0.003]
 [175.129 177.000 0.011]
 [174.774 175.000 0.001]
 [166.505 175.000 0.049]
 [151.429 149.000 0.016]
 [191.396 192.000 0.003]]


In [9]:
data_in[5, :]

array([ 53.,  46.,  55., 101.])