Fibonacci_squences

In [1]:
fibonacci_squences = [1, 1]
for n in range(2, 15):
    fibonacci_numbers = fibonacci_squences[n-2] + fibonacci_squences[n-1]
    fibonacci_squences.append(fibonacci_numbers)
    print(fibonacci_squences)

[1, 1, 2]
[1, 1, 2, 3]
[1, 1, 2, 3, 5]
[1, 1, 2, 3, 5, 8]
[1, 1, 2, 3, 5, 8, 13]
[1, 1, 2, 3, 5, 8, 13, 21]
[1, 1, 2, 3, 5, 8, 13, 21, 34]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610]


Taylor expansion
$e^{x} = \sum_{k=0}^{\infty} \frac{x^{k}}{k!}$

In [2]:
def factorial(N):
    product = 1 
    for n in range(2, N+1):
        product *= n

    return product

In [3]:
factorial(5)

120

In [4]:
sum(1/factorial(k) for k in range(0, 101))

2.7182818284590455

#Searching for solutions
we can use `for` loops to search for integer solutions of equations. For example, suppose we would like to find all representations of a positive integer $N$ as a sum of two squares. In other words we want to find all integer solutions $(x, y)$ of the equation:
$$x^{2}+y^{2} = N$$
Write a function called `reps_sum_squares` which takes an integer $N$ and finds all representations of $N$ as a sum of squares $x^{2}+y^{2}=N$ for $0\leq x \leq y$. The function returns the representations as a list of tuples. For example, if $N=50$, then $1^{2}+7^{2} = 50$ and $5^{2}+5^{2}=50$ and the function returns the list `[(1, 7), (5, 5)]`.

Let's outline our approach before we write any code:
1. Given $x\leq y$, the largest positive value for $x$ is $\sqrt{\frac{N}{2}}$
2. For $x \leq \sqrt{\frac{N}{2}}$, the pair $(x, y)$ is a solution if $N-x^{2}$ is a square
3. Define a helper function called `is_square` to test if an integer is square


In [4]:
def is_square(N):
    return round(N**0.5)**2 == N 

def reps_sum_squares(N):
    reps = []
    if is_square(N/2):
        max_x = round((N/2)**0.5)
    else:
        max_x = int((N/2)**0.5)
    
    for x in range(0, max_x + 1):
        y_squared = N - x**2
        if is_square(y_squared):
            y = round(y_squared**0.5)

            reps.append((x, y))

    return reps    


In [5]:
reps_sum_squares(1105)

[(4, 33), (9, 32), (12, 31), (23, 24)]

What is the smallest integer which can be expressed as the sum of squares in 5 different ways?

In [6]:
N = 1105
num_reps = 4
while num_reps < 5:
    N += 1
    reps = reps_sum_squares(N)
    num_reps =len(reps)

print(N, ":", reps_sum_squares(N))

4225 : [(0, 65), (16, 63), (25, 60), (33, 56), (39, 52)]


#Numpy
Numpy is the core Python package for numerical computing. The main features of NumPy are:
* N-dimensional array object `ndarray`
* Vectorized operations and functions which broadcast across arrays for fast computation

To get started with NumPy, let's adopt the standard convention and import it using the name `np`:

In [1]:
import numpy as np

# NumPy Arrays
The fundamental object provided by the NumPy package is the `ndarray`. We can think of a 1D(1-dimensional) `ndarray` as a list, a 2D (2-dimensional) `ndarray` as a matrix, a 3D(3-dimensional) `ndarray` as a 3-tensor (or a "cube" of numbers), and so on. See the NumPy tutorial for more about NumPy arrays. 

## Creating Arrays
The function `numpy.array` creates a NumPy array form a Python sequence such as a list, a tuple or a list of lists. For example, create a 1D NumPy array from a Python list:

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]



Notice that when we print a NumPy array it looks a lot like a Python list except that the entries are seperated by spaces whereas entries in a Python list are separated by commas:

In [3]:
print([ 1, 2, 3, 4, 5])

[1, 2, 3, 4, 5]


Notice also that a NumPy array is displayed slightly differently when output by a cell (as opposed to being explicitly printed to output by the `print` function):

In [5]:
a

array([1, 2, 3, 4, 5])

Use the built-in function `type` to verify the type:

In [6]:
type(a)

numpy.ndarray

Create a 2d NumPy array from a Python list of lists:

In [7]:
M = np.array([[1, 2, 3], [4, 5, 6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [8]:
type(M)

numpy.ndarray

Create an n-dimensional NumPy array from nested Python lists. For example, the following is a 3D NumPy array:

In [10]:
N = np.array([[ [1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(N)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


|Function|Description|
|---:|:---|
|numpy.array(a)|Create n-dimensional NumPy array from seqeunce a|
|numpy.linspace(a, b, N)|Create 1D NumPy array with `N` equally spaced values from `a` to `b` (inclusively)|
|numpy.arrange(a, b, step)|Create 1D NumPy array with values from `a` to `b` (exclusively) incremented by `step`|
|numpy.zeros(N)|Create 1D NumPy array of zeros of length N|
|numpy.zeros((n, m))|Create 2D NumPy array of zeros with n rows and m columns|
|numpy.ones(N)|Create 1D NumPy array of ones of length N|
|numpy.ones((n, m))| Create 2D NumPy array of ones with n rows and m columns|
|numpy.eye(N)|Create 2D NumPy array|


Create a 1D NumPy array with 11 equally spaced values from 0 to 1:

In [11]:
x = np.linspace(0, 1, 11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Create a 1D NumPy array with values from 0 to 20 (exclusively) incremetned by 2.5:

In [13]:
y = np.arange(0, 20, 2.5)
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


These are the functions that we'll use most often when creating NumPy arrays. The function `numpy.linspace` works best when we know the number of points we want in the array, and `numpy.arange` works best when we know step sie between values in the array.

Create a 1D NumPy array of zeros of length 5:

In [14]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


Create a 2D NumPy array of zeros with 2 rows and 5 columns:

In [15]:
M = np.zeros((2, 5))
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create a 1D NumPy array on ones of length 7:

In [17]:
w = np.ones(7)
print(w)

[1. 1. 1. 1. 1. 1. 1.]


Create a 2D NumPy array of ones with 3 rows and 2 columns:

In [18]:
N = np.ones((3, 2))
print(N)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Create the identity matrix of size 10:

In [19]:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## Array Datatype
NumPy arrays are homogeneous: all entries in the array are the same datatype. We will only work with numeric arrays and our arrays will contain either integers, floats, complex numbers or booleans. These are different kinds of datatypes provided by NumPy for different applications but we'll mostly be working with the default integer type `numpy.int64` and the default float type `numpy.float64`. These are very similar to the built-in Python datatypes `int` and `float` but with some differences that we won't go into. check out the NumPy documentation on numeric datatypes for more information.

The most important point for now is to know how to determine if a NumPy array contains integers elements or float elements. We can access the datatype of a NumPy array by its `.dtype` attribute. For example, create a 2D NumPy array from a list of lists of integers:

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


We expect the datatype of `A` to be integers and we verify:

In [21]:
A.dtype

dtype('int64')

Most of the other NumPy functions which create arrays use the `numpy.float64` datatype by default. For example, using `numpy.linspace`:

In [22]:
u = np.linspace(0, 1, 5)
print(u)

[0.   0.25 0.5  0.75 1.  ]


In [23]:
u.dtype

dtype('float64')

Notice that numbers are printed with a decimal point when the datatype of the NumPy array is any kind of float.

## Dimension, Shape and Size
We can think of a 1D NumPy array as a list of numbers, a 2D NumPY array as a matrix, a 3D NumPy array as a cube of numbers, and so on. Given a NumPy array, we can find out how many dimensions it has by accessing its `.ndim` attribute. The result is a number telling us how many dimensions it has.

For example, create a 2D NumPy array:

In [24]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
A.ndim

2

The result tells us that `A` has 2 dimensions. The first dimension corresponds to the vertical directoin counting the rows and the second dimension corresponds to the horizontal direction counting the columns.

We can find out how many rows and columns `A` has by accessing its `.shape` attribute:

In [26]:
A.shape

(3, 2)

The result is a tuple `(3, 2)` of length 2 which means that `A` is a 2D array with 3 rows and 2 columns.

We can also find out how many entries `A` has in total by accessing its `.size` attribute:

In [27]:
A.size

6

This is the expected result since we know that `A` has 3 rows and 2 columns and therefore 2(3) = 6 total entries.

Create a 1D NumPy array and inspect its dimension, shape and size:

In [28]:
r = np.array([9, 3, 1, 7])
print(r)

[9 3 1 7]


In [29]:
r.ndim

1

In [30]:
r.shape

(4,)

In [31]:
r.size

4

The variabel `r` is assigned to a 1D NumPy array of length 4. Notice that `r.shape` is a tuple with a single entry `(4, 1)`.

## Slicing and Indexing
Accessing the entries in an array is called indexing and accessing rows and columns (or subarrays) is called slicing. See the NumPy documnentation for more information about indexing and slicing.

Create a 2D array of integers:

In [32]:
v = np.linspace(0, 5, 11)
print(v)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


Access the entries in a 1D array using the square brackets notation just like a Python list. For example, access the entry at index 3:

In [33]:
v[3]

1.5

Notice that NumPy array indices start at 0 just like Python sequences.

Create a 2D array of integers:

In [34]:
B = np.array([[6, 5, 3, 1, 1], [1, 0, 4, 0, 1], [5, 9, 2, 2, 9]])
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


Access the entries in a 2D array using the square brackets with 2 indices. In particular, access the entry at row index 1 and column index 2:

In [35]:
B[1, 2]

4

Access the top left entry in the array:

In [36]:
B[0, 0]

6

Negative indices work for NumPy arrays as they do for Python sequences. Access the bottom right entry in the array:

In [37]:
B[-1, -1]

9

Access the row at index 2 using the colon `:` syntax:

In [39]:
B[2, :]

array([5, 9, 2, 2, 9])

Access the column at index 3:

In [40]:
B[:, 3]

array([1, 0, 2])

Select the subarray of rows at index 1 and 2, and columns at index 2, 3 and 4:

In [41]:
subB = B[1:3, 2:5]
print(subB)

[[4 0 1]
 [2 2 9]]


Slices of NumPy arrays are again NumPy arrays but possibly of a different dimension:

In [42]:
subB.ndim

2

In [43]:
subB.shape

(2, 3)

In [44]:
type(subB)


numpy.ndarray

The variable `subB` is assigned to a 2D NumPy array of shape 2 by 2.

Let's do the same for the column at index 2:

In [45]:
colB = B[:, 2]
print(colB)

[3 4 2]


In [46]:
colB.ndim

1

In [47]:
colB.shape

(3,)

In [49]:
type(colB)

numpy.ndarray

The variable `colB` is assigned to a 1D NumPy array of length 3.

# Stacking
We can build bigger arrays out of smaller arrays of by stacking along different dimensions using the functions `numpy.hstack` and `numpy.vstack`.

Stack 3 different 1D NumPy arrays of length 3 vertically forming a 3 by 3 matrix:

In [50]:
x = np.array([1, 1, 1])
y = np.array([2, 2, 2])
z = np.array([3, 3, 3])
vstacked = np.vstack((x, y, z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


Stack 1D NumPy arrays horizontally to create another 1D array:

In [51]:
hstacked = np.hstack((x, y, z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


Use `numpy.hstack` and `numpy.vstack` to build the matrix T where
$$ T = \begin{bmatrix}
1 & 1 & 2 & 2\\
1 & 1 & 2 & 2\\
3 & 3 & 4 & 4\\
3 & 3 & 4 & 4
\end{bmatrix}

In [52]:
A = np.ones((2, 2))
B = 2*np.ones((2, 2))
C = 3*np.ones((2, 2))
D = 4*np.ones((2, 2))
A_B = np.hstack((A, B))
print(A_B)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]]


In [53]:
C_D = np.hstack((C, D))
print(C_D)

[[3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [54]:
T = np.vstack((A_B, C_D))
print(T)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


### Copies versus Views
Under construction

## Operatoins and Functions

### Array Operations
Arithmetic operators including addition `+`, subtraction `-`, multiplication `*`, division `/` and exponential `**` are applied to arrays elementwise. For addition and substraction, these are the familiar vector operations we see in linear algebra:

In [55]:
v = np.array([1, 2, 3])
w = np.array([1, 0, -1])

In [56]:
v + w

array([2, 2, 2])

In [57]:
v - w

array([0, 2, 4])

In the smae way, array multiplication and divison are performed element by element:

In [58]:
v * w

array([ 1,  0, -3])

In [59]:
w / v

array([ 1.        ,  0.        , -0.33333333])

The exponent operator `**` also acts element by element in the array:

In [60]:
v ** 2

array([1, 4, 9])

Let's see these operations for 2D arrays:

In [61]:
A = np.array([[3, 1], [2, -1]])
B = np.array([[2, -2], [5, 1]])

In [62]:
A + B

array([[ 5, -1],
       [ 7,  0]])

In [64]:
A - B

array([[ 1,  3],
       [-3, -2]])

In [65]:
A / B

array([[ 1.5, -0.5],
       [ 0.4, -1. ]])

In [66]:
A * B

array([[ 6, -2],
       [10, -1]])

In [67]:
A ** 2

array([[9, 1],
       [4, 1]])

#### Notice that array multiplication and exponentiation are performed elmentwise.
In Python 3.5+, the symbol `@` computes matrix multiplicatoin for NumPy arrays:

In [68]:
A @ B

array([[11, -5],
       [-1, -5]])

Matrix powers are performed by the function `numpy.linalg.matrix_power`. It's a long function name and so it's convenient to import it with a shorter name:

In [69]:
from numpy.linalg import matrix_power as mpow

Compute A:

In [70]:
mpow(A, 3)

array([[37,  9],
       [18,  1]])

Equivalently, use the `@` operator to compute $A^{3}$:

In [71]:
A @ A @ A

array([[37,  9],
       [18,  1]])

### Broadcasting
We know from linear algebra that we can only add matrices of the same size. Broadcasting is a set of NumPy rules which relaxes this constraint and allows us to combine a smaller array with a bigger when it makes sense.

For example, suppose we want to create a 1D NumPy array of $y$ values for $x = 0.0, 0.25, 0.5, 0.75, 1.0$ for the function $y = x^{2} + 1$. From what we've seen so far, it makes sense to create `x`, then `x**2` and then add an array of ones `[1. 1. 1. 1. 1.]`:

In [72]:
x = np.array([0, 0.25, 0.5, 0.75, 1.0])
y = x**2 + np.array([1, 1, 1, 1, 1])
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


An example of broadcasting in NumPy is the following equivalent operation:

In [73]:
x = np.array([0, 0.25, 0.5, 0.75, 1.0])
y = x**2 + 1
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


The number 1 is a scalar and we are adding to a 1D NumPy array of length 5. The broadcasting rule in this case is to broadcast the scalar value 1 across the larger array. The result is a simpler syntax for a very comman operation.

Let's try another example. What happens when we try to add a 1D NumPy array of length 4 to a 2D NumPy array of size 3 by 4?

In [74]:
u = np.array([1, 2, 3, 4])
print(u)

[1 2 3 4]


In [75]:
A = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
print(A)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [76]:
result = A + u
print(result)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


The 1D NumPy array is broadcast across the 2D array because the length of the first dimension in each array are equal!

## Array Functions
These are many array functions we can use to compute with NumPy arrays. The following is a partial list and we'll look closer at mathematical functions in the next section.

|`numpy.sum`|`numpy.prod`|`numpy.mean`|
|`numpy.max`|`numpy.min`|`numpy.std`|
|`numpy.argmax`|`numpy.argmin`|`numpy.var`|


Create a 1D NumPy array with random values and compute:

In [78]:
arr = np.array([8, -2, 4, 7, -3])
print(arr)

[ 8 -2  4  7 -3]


Compute the mean of the values in the array:

In [79]:
np.mean(arr)

2.8

Verify the mean once more:

In [80]:
m = np.sum(arr)/ arr.size
print(m)

2.8


Find the index of the maximum element in the array:

In [81]:
max_i = np.argmax(arr)
print(max_i)

0


Verify the maximum value in the array:

In [82]:
np.max(arr)

8

In [83]:
arr[max_i]

8

Array functions apply to 2D arrays as wll(and N-dimensional arrays in general) with the added feature that we can choose to apply array functions to the entire array, down the columns or across the rows (or any axis).


Create a 2D NumPy array with random values and compute the sum of all the entries:

In [84]:
M = np.array([[2, 4, 2], [2, 1, 1], [3, 2, 0], [0, 6, 2]])
print(M)

[[2 4 2]
 [2 1 1]
 [3 2 0]
 [0 6 2]]


In [85]:
np.sum(M)

25

The funcion `numpy.sum` also takes a keyworkd argument `axis` which determine along which dimension to compute the sum:

In [86]:
np.sum(M, axis=0)

array([ 7, 13,  5])

In [87]:
np.sum(M, axis=1)

array([8, 4, 5, 8])

## Mathematica Functions
Mathematical functions in NumPy are called universal functions and are vectorized. Vectorized functions operate elementwise on arrays producing arrays as output and are built to compute values across arrays very quickly. The following is a partial list of mathematical functions:
|`numpy.sin`|`numpy.cos`|`numpy.tan`|
|`numpy.exp`|`numpy.log`|`numpy.log10`|
|`numpy.arcsin`|`numpy.arccos`|`numpy.arctan`|

Compute the values $sin(2\pi x)$ for $ x = 0, 0.25, 0.5, \dots 1.75$:

In [89]:
x = np.arange(0, 1.25, 0.25)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [90]:
np.sin(2*np.pi*x)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

We expect the array `[0. 1. 0. -1. 0.]` however there is (as always with floating point numbers) some rounding errors in the result. In numerical computingm, we can interpret a number such as $10^{-16}$ as 0

Compute the values $\log_{10}(x)$ for $ x=1, 10, 100, 1000, 10000$:

In [91]:
x = np.array([1, 10, 100, 1000, 10000])
print(x)

[    1    10   100  1000 10000]


In [92]:
np.log10(x)

array([0., 1., 2., 3., 4.])

Note that we can also evaluate mathematical functions with scalar values:

In [93]:
np.sin(0)

0.0

NumPy also provides familiar mathematical constants such as $\pi$ and $e$:

In [94]:
np.pi

3.141592653589793

In [95]:
np.e

2.718281828459045

For example, verify the limit $$ \lim_{x \to \infty} arctan(x)  = \frac{\pi}{2}$$
by evaluating $\text{arctan}(x)$ for some (arbitrary) large value x:

In [96]:
np.arctan(10000)

1.5706963267952299

In [97]:
np.pi/2

1.5707963267948966

## Random Number Generators
The subpackage `numpy.random` contains functions to generate NumPy arrays of random numbers sampled from different distributions. The following is a partial list of distributions:
|Funcions|Description|
|:---|:---|
|`numpy.random.rand(d1, ..., dn)`|Create a NumPy array (with shape (d1, ..., dn)) with entries sampled uniformly from (0, 1)|
|`numpy.random.randn(d1, ..., dn)`|Create a NumPy array (with shape (d1, ..., dn)) with entries sampled from the standard normal distribution|
|`numpy.random.randint(a, b, size)`|Create a NumPy array (with shape size) with integer entries from low (inclusive) to high (exclusive)

Sample a random number from the uniform distribution:


In [98]:
np.random.rand()

0.6244372987557864

Sample 3 random numbers:

In [99]:
np.random.rand(3)

array([0.36561888, 0.46888483, 0.29150027])

In [100]:
np.random.rand(2, 4)



array([[0.51605264, 0.14728716, 0.60287325, 0.0593755 ],
       [0.11754998, 0.66270809, 0.06838298, 0.31295693]])

Create 2D NumPy array of random samples:

In [101]:
np.random.randn()

0.33226029834167786

In [102]:
np.random.randn(3)

array([-0.65180294,  0.03021703,  0.42332605])

In [103]:
np.random.randn(3, 1)



array([[ 0.82803289],
       [ 0.43543977],
       [-2.89028471]])

Random integers sampled uniformly from various intervals:

In [104]:
np.random.randint(-10, 10)

-6

In [105]:
np.random.randint(0, 2, (4, 8))


array([[0, 0, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [106]:
np.random.randint(-9, 10, (5, 2))

array([[-7,  4],
       [ 8, -2],
       [ 2, -8],
       [ 9, -6],
       [ 0, -4]])

## Examples

###

# Matplotlib