# Linear Algebra with SciPy
The main Python package for linear algebra is the SciPy subpackage `scipy.linalg` which builds on NumPy. Let's import both packages:

In [1]:
import numpy as np
import scipy.linalg as la

## NumPy Arrays
### Array Attributes
Create a 1D (one-dimensional) NumPy array and verify its dimensions, shape and size.

In [2]:
a = np.array([1, 3, -2, 1])
print(a)

[ 1  3 -2  1]


Verify the number of dimensions:

In [3]:
a.ndim

1

Verify the shape of the array:

In [4]:
a.shape

(4,)

The shape of an array is returned as a Python tuple. The output in the cell above is a tuple of length 1. And we verify the size of the array(i.e. the total number of entries in the array):

In [5]:
a.size

4

Create a 2D(two-dimensional) NumPy array(i.e. matrix):

In [6]:
M = np.array([[1, 2], [3, 7], [-1, 5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


Verify the number of dimensions:

In [7]:
M.ndim

2

Verify the shape of the array:

In [8]:
M.size

6

Select a row or column from a 2D NumPy array and we get a 1D array:

In [9]:
col = M[:, 1]
print(col)

[2 7 5]


Verify the number of dimensions of the slice:

In [10]:
col.ndim

1

Verify the shape and size of the slice:

In [11]:
col.shape

(3,)

In [12]:
col.size

3

When we select a row of column from a 2D NumPy array, the result is a 1D NumPy array. However, we may want to select a column as a 2D column vector. 
This requires us to use the reshape method.
\\
For example, create a 2D column vector from the 1D slice selected from the matrix `M` above:

In [13]:
print(col)

[2 7 5]


In [14]:
column = np.array([2, 7, 5]).reshape(3, 1)
print(column)

[[2]
 [7]
 [5]]


Verify the dimensions, shape and size of the array:

In [15]:
print('Dimensions:', column.ndim)
print("Shape:", column.shape)
print("Size:", column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


The variables `col` and `column` are different types of objects even though they have the "same" data.

In [16]:
print(col)

[2 7 5]


In [17]:
print('Dimensions:', col.ndim)
print("Shape:", col.shape)
print("Size:", col.size)

Dimensions: 1
Shape: (3,)
Size: 3


## Matrix Operations and Functions
### Arithmetic Operations
Recall that arithmetic array operations `+`,`-`,`/`,`*` and `**` are performed elementwise on NumPy arrays. Let's create a NumPy array and do some computations:

In [18]:
M = np.array([[3, 4], [-1, 5]])
print(M)

[[ 3  4]
 [-1  5]]


In [19]:
M * M

array([[ 9, 16],
       [ 1, 25]])

### Matrix Multiplication
We use the `@` operator to do matrix multiplication with NumPy arrays:

In [20]:
M @ M

array([[ 5, 32],
       [-8, 21]])

Let's compute $2I+3A-AB$ for 
$$ A = \begin{bmatrix} 1 & 3\\ -1 & 7 \end{bmatrix}, B=\begin{bmatrix} 5 & 2\\ 1& 2\end{bmatrix}$$ 
and $I$ is the identity matrix of size 2:

In [21]:
A = np.array([[1, 3], [-1, 7]])
print(A)

[[ 1  3]
 [-1  7]]


In [22]:
B = np.array([[5, 2], [1, 2]])
print(B)

[[5 2]
 [1 2]]


In [23]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [24]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

#### Matrix Powers
There's no symbol for matrix powers and so we must import the function `matrix_power` from the subpackage `numpy.linalg`.

In [25]:
from numpy.linalg import matrix_power as mpow

In [26]:
M = np.array([[3, 4], [-1, 5]])
print(M)

[[ 3  4]
 [-1  5]]


In [27]:
mpow(M, 2)

array([[ 5, 32],
       [-8, 21]])

In [28]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

Compare with the matrix multiplicatoin operator:

In [29]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [30]:
mpow(M, 3)

array([[-17, 180],
       [-45,  73]])

In [31]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

#### Transpose
We can take the transpose with `.T` attribute:

In [32]:
print(M)

[[ 3  4]
 [-1  5]]


In [33]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


Notice that $MM^{T}$ is a symmetric matrix:

In [34]:
M @ M.T

array([[25, 17],
       [17, 26]])

#### Inverse
We can find the inverse using the funciton `scipy.linalg.inv`:

In [35]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [36]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### Trace
We can find the trace of a matrix using the function `numpy.trace`:

In [37]:
np.trace(A)

5

In [38]:
la.det(A)

-2.0

### Examples
#### Characteristic Polynomials and Cayley-Hamiltion Theoren
The characteristic polynomial of 2 by 2 square matrix $A$ is
$$p_{A}(\lambda) = \text{det}(A-\lambda I)=\lambda^{2} - \text{tr}(A)\lambda + \text{det}(A)$$
The Cayley-Hamiltion Theorem states that any square matrix satisfies its characteristic polynomial. For a matrix $A$ of size 2, this means that
$$p_{A}(A) = A^{2} - \text{tr}(A)A + \text{det}(A) I = 0$$
Let's verify the Cayle-Hamilton Theorem for a few diffrerent matrices.

In [39]:
print(A)

[[1 2]
 [3 4]]


In [40]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)
A @ A - trace_A * A + det_A * I

array([[0., 0.],
       [0., 0.]])

Let's do this again for some random matrices:

In [41]:
N = np.random.randint(0, 10, [2, 2])
print(N)

[[0 9]
 [3 2]]


In [42]:
trace_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)
N @ N - trace_N * N + det_N * I

array([[0., 0.],
       [0., 0.]])

### Projections
The formula to project a vector $v$ onto a vector $w$ is
$$\text{proj}_{w}(v) = \frac{v \cdot w}{w \cdot w}w$$
Let's write a function called `proj` which computes the projection $v$ onto $w$.

In [43]:
def proj(v, w):
    '''Project vector v onto w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v*w)/np.sum(w*w) * w

In [44]:
proj([1, 2, 3], [1, 1, 1])

array([2., 2., 2.])

## Eigenvalues and Eigenvectors

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

### Definition
Let $A$ be a square matrix. A non-zero vector $v$ is an eigenvector for $A$ with eigenvalue $\lambda$ if $$Av = \lambda v$$
Rearranging the equation, we see that $v$ is a solution of the homogeneous system of equations
$$(A-\lambda I) v = 0$$
where $I$ is the identity matrix of size $n$. Non-trivial solutions exies only if the matrix $A-\lambda I$ is singular which means $\text{det}(A-\lambda I) = 0 $. Therefore eigenvalues of $A$ are roos of the characteristic polynomial
$$p(\lambda) = \text{det}(A-\lambda I)$$

### scipy.linalg.eig
The funciton `scipy.linalg.eig` computes eigenvalues and eigenvectors of a square matrix $A$.
Let's consider a simple example with a diagonal matrix:

In [46]:
A = np.array([[1, 0], [0, -2]])
print(A)

[[ 1  0]
 [ 0 -2]]


The function `la.eig` returns a tuple `(eigvals, eigvecs)` where `eigvals` is a 1D NumPy array of complex numbers giving the eigenvalues of $A$, and `eigvecs` is a 2D NumPy array with the corresponding eigenvectors in the columns:

In [47]:
results = la.eig(A)

The eigenvalues of $A$ are:

In [48]:
print(results[0])

[ 1.+0.j -2.+0.j]


The corresponding eigenvectors are:

In [49]:
print(results[1])

[[1. 0.]
 [0. 1.]]


We can unpact the tuple:

In [50]:
eigvals, eigvecs = la.eig(A)
print(eigvals)

[ 1.+0.j -2.+0.j]


In [51]:
print(eigvecs)

[[1. 0.]
 [0. 1.]]


If we know that the eigenvalues are real numbers(i.e. if $A$ is symmetric), then we can use the NumPy array method `.real` to convert the array of eigenvalues to real numbers:

In [52]:
eigvals = eigvals.real
print(eigvals)

[ 1. -2.]


Notice that the position of an eigenvalue in the array `eigvals` correspond to the column in `eigvecs` with its eigenvector:

In [53]:
lambda1 = eigvals[1]
print(lambda1)

-2.0


In [54]:
v1 = eigvecs[:, 1].reshape(2,1)
print(v1)

[[0.]
 [1.]]


In [55]:
A @ v1

array([[ 0.],
       [-2.]])

In [56]:
lambda1 * v1

array([[-0.],
       [-2.]])

#### Examples
##### Symmetric Matrices
The eigenvalues of a symmetric matrix are always real and the eigenvectors are always orthogonal! Let's verify these facts with some random matrices:

In [57]:
n = 4
P = np.random.randint(0, 10, (n,n))
print(P)

[[5 3 8 2]
 [5 6 2 6]
 [2 6 1 0]
 [1 3 9 7]]


Create the symmetric matrix $S=PP^{T}$:

In [58]:
S = P @ P.T
print(S)

[[102  71  36 100]
 [ 71 101  48  83]
 [ 36  48  41  29]
 [100  83  29 140]]


Let's unpack the eigenvalues and eigenvectors of $S$:

In [59]:
evals, evecs = la.eig(S)
print(evals)

[302.40634743+0.j  51.2877515 +0.j  21.81417263+0.j   8.49172844+0.j]


The eigenvalues all have zero imaginary part and so they are indeed real numbers:

In [60]:
evals = evals.real
print(evals)

[302.40634743  51.2877515   21.81417263   8.49172844]


The corresponding eigenvectors of $A$ are:

In [61]:
print(evecs)

[[ 0.5371343   0.18096882 -0.74066309  0.36077032]
 [ 0.50617777 -0.58331251  0.44525206  0.45307967]
 [ 0.23700246 -0.58545404 -0.31601193 -0.70796177]
 [ 0.63174413  0.53314198  0.39154215 -0.40417042]]


Let's check that the eigenvectors are orthogonal to each other:

In [62]:
v1 = evecs[:,0] # First column is the first eigenvector
print(v1)

[0.5371343  0.50617777 0.23700246 0.63174413]


In [63]:
v2 = evecs[:, 1]
print(v2)

[ 0.18096882 -0.58331251 -0.58545404  0.53314198]


In [64]:
v1 @ v2

-1.1102230246251565e-16

The dot product of eigenvectors $v_{1} and v_{2}$ is zero(the numver above is very close to zero and is due to rounding errors in the computations) and so they are orthogonal!

#### Diagonalization
A square matrix $M$ is diagonalizable if ti is similar to a diagonal mattrix. In other words, $M$ is diagonalizable if there exists an invertible matrix $P$ such that $D = P^{-1}MP$ is a diagonal matrix.

A beautiful result in linear algebra is that a square matrix $M$ of size $n$ is diagonalizable if and only if $M$ has $n$ independent eigenvectors. Furthermore, $M=PDP^{-1}$ where the oclumns of $P$ are the eigenvectors of $M$ and $D$ has corresponding eigenvalues along the diagonal.

Let's use this to construct a matrix with given eigenvalues $\lambda_{1}=3, \lambda_{2}=1$, and eigenvectors $v_{1} = \left[1,1\right]^{T}, v_{2} = \left[1, -1 \right]^{T}$.

In [65]:
P = np.array([[1, 1], [1, -1]])
print(P)

[[ 1  1]
 [ 1 -1]]


In [66]:
D = np.diag((3, 1))
print(D)

[[3 0]
 [0 1]]


In [67]:
M = P @ D @ la.inv(P)
print(M)

[[2. 1.]
 [1. 2.]]


Let's verify that the eigenvalues of $M$ are 3 and 1:

In [68]:
evals, evecs = la.eig(M)
print(evals)

[3.+0.j 1.+0.j]


Verify the eigenvectors:

In [69]:
print(evecs)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


##### Matrix Powers
Let $M$ be a square matrix. Computing powers of $M$ by matrix multiplication $$M^{k}=\underbrace{MM \cdots M}_{k}$$
is computationally expensive. Instead, let's use diagonalization to compute $M^{k}$ more efficiently
$$M^{k} =(PDP^{-1})^{k} = \underbrace{PDP^{-1}PDP^{-1} \cdots PDP^{-1}}_{k} = PD^{k}P^{-1}$$
Let's compute $M^{20}$ both ways and compare execution time.

In [70]:
Pinv = la.inv(P)

In [71]:
k = 20

In [72]:
%%timeit
result = M.copy()
for _ in range(1, k):
    result = result @ M

31.5 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Let's use diagonalization to do the same computation.

In [73]:
%%timeit
P @ D**k @ Pinv

4.97 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Diagonalization computes $M^{k}$ much faster!